/**
 * SQL Query Standar untuk Mendeteksi Item Margin Minus di Database PostgreSQL Indogrosir
 */
const DEFAULT_MARGIN_QUERY = `
SELECT PRD_KODEDIVISI DIV,
  PRD_PRDCD PLU,
  PRD_DESKRIPSIPANJANG DESKRIPSI,
  PRD_FRAC FRAC,
  PRD_UNIT UNIT,
  PRD_KODETAG TAG,
  ST_SALDOAKHIR LPP,
  PRD_HRGJUAL HRG,
  PRMD_HRGJUAL HRG_P,
  LCOST LCOST_PCS,
  ACOST ACOST_PCS,
  ACOST_INCLUDE A_COST_INC,
  MARGIN_A MARGIN,
  MARGIN_L MARGIN_LCOST,
  MARGIN_A_MD,
  MARGIN_L_MD,
  MARGIN_A_MDS,
  MARGIN_L_MDS
FROM
  (SELECT PRD_KODEDIVISI,
    PRD_PRDCD,
    PRD_DESKRIPSIPANJANG,
    PRD_FRAC,
    PRD_UNIT,
    PRD_KODETAG,
    ST_SALDOAKHIR,
    PRD_HRGJUAL,
    PRMD_HRGJUAL,
    LCOST,
    ACOST,
    ACOST_INCLUDE,
    MARGIN_A,
    MARGIN_L,
    
        CASE
          WHEN PRD_UNIT='KG'
          THEN (((PRMD_HRGJUAL-(ST_AVGCOST*PRD_FRAC/1000))/PRMD_HRGJUAL)*100)
          WHEN COALESCE(prd_flagbkp1,'T') ='Y' and COALESCE(prd_flagbkp2,'T') ='Y'
          THEN (((PRMD_HRGJUAL/1.11)-(ST_AVGCOST*PRD_FRAC))/(PRMD_HRGJUAL/1.11)*100)
          ELSE (((PRMD_HRGJUAL-(ST_AVGCOST*PRD_FRAC))/PRMD_HRGJUAL)*100)
        END AS MARGIN_A_MD,
   
        CASE
          WHEN PRD_UNIT='KG'
          THEN (((PRMD_HRGJUAL-(ST_LASTCOST*PRD_FRAC/1000))/PRMD_HRGJUAL)*100)
          WHEN COALESCE(prd_flagbkp1,'T') ='Y' and COALESCE(prd_flagbkp2,'T') ='Y'
          THEN (((PRMD_HRGJUAL/1.11)-(ST_LASTCOST*PRD_FRAC))/(PRMD_HRGJUAL/1.11)*100)
          ELSE (((PRMD_HRGJUAL-(ST_LASTCOST*PRD_FRAC))/PRMD_HRGJUAL)*100)
        END AS MARGIN_L_MD,

        -- Kolom 1: MARGIN_A_MD (menggunakan ST_AVGCOST)
        CASE
            WHEN PRD_UNIT = 'KG'
                  THEN (((PRMD_HRGJUAL - (ST_AVGCOST * PRD_FRAC / 1000)) / PRMD_HRGJUAL) * 100)
            WHEN COALESCE(prd_flagbkp1, 'T') = 'Y' AND COALESCE(prd_flagbkp2, 'T') = 'Y'
                  THEN CASE 
                      WHEN SETT_PROMOMD IS NULL 
                            THEN (((PRD_HRGJUAL / 1.11) - (ST_AVGCOST * PRD_FRAC)) / (PRD_HRGJUAL / 1.11) * 100)
                      ELSE (((PRMD_HRGJUAL / 1.11) - (ST_AVGCOST * PRD_FRAC)) / (PRMD_HRGJUAL / 1.11) * 100)
                  END
            ELSE CASE 
                      WHEN SETT_PROMOMD IS NULL 
                            THEN (((PRD_HRGJUAL - (ST_AVGCOST * PRD_FRAC)) / PRD_HRGJUAL) * 100)
                      ELSE (((PRMD_HRGJUAL - (ST_AVGCOST * PRD_FRAC)) / PRMD_HRGJUAL) * 100)
                  END
        END AS MARGIN_A_MDS,
    
        -- Kolom 2: MARGIN_L_MD (menggunakan ST_LASTCOST)
        CASE
            WHEN PRD_UNIT = 'KG'
                  THEN (((PRMD_HRGJUAL - (ST_LASTCOST * PRD_FRAC / 1000)) / PRMD_HRGJUAL) * 100)
            WHEN COALESCE(prd_flagbkp1, 'T') = 'Y' AND COALESCE(prd_flagbkp2, 'T') = 'Y'
                  THEN CASE 
                      WHEN SETT_PROMOMD IS NULL 
                            THEN (((PRD_HRGJUAL / 1.11) - (ST_LASTCOST * PRD_FRAC)) / (PRD_HRGJUAL / 1.11) * 100)
                      ELSE (((PRMD_HRGJUAL / 1.11) - (ST_LASTCOST * PRD_FRAC)) / (PRMD_HRGJUAL / 1.11) * 100)
                  END
            ELSE CASE 
                      WHEN SETT_PROMOMD IS NULL 
                            THEN (((PRD_HRGJUAL - (ST_LASTCOST * PRD_FRAC)) / PRD_HRGJUAL) * 100)
                      ELSE (((PRMD_HRGJUAL - (ST_LASTCOST * PRD_FRAC)) / PRMD_HRGJUAL) * 100)
                  END
        END AS MARGIN_L_MDS
        
  FROM(SELECT PRD_KODEDIVISI,
  PRD_PRDCD,
  PRD_DESKRIPSIPANJANG,
  PRD_FRAC,
  PRD_UNIT,
  PRD_KODETAG,
  ST_SALDOAKHIR,
  PRD_HRGJUAL,
  ST_LASTCOST,prd_flagbkp2,prd_flagbkp1,ST_AVGCOST,
  CASE
    WHEN PRD_UNIT='KG'
    THEN (ST_LASTCOST*PRD_FRAC)/1000
    ELSE ST_LASTCOST *PRD_FRAC
  END AS LCOST,
  CASE
    WHEN PRD_UNIT='KG'
    THEN (ST_AVGCOST*PRD_FRAC)/1000
    ELSE ST_AVGCOST *PRD_FRAC
  END AS ACOST,
  CASE
    WHEN PRD_UNIT='KG'
    THEN ((ST_AVGCOST*PRD_FRAC)/1000)*1.11
    ELSE (ST_AVGCOST *PRD_FRAC)*1.11
  END AS ACOST_INCLUDE,
   
        CASE
          WHEN PRD_UNIT='KG'
          THEN (((PRD_HRGJUAL-(ST_AVGCOST*PRD_FRAC/1000))/PRD_HRGJUAL)*100)
          WHEN COALESCE(prd_flagbkp1,'T') ='Y' and COALESCE(prd_flagbkp2,'T') ='Y'
          THEN (((PRD_HRGJUAL/1.11)-(ST_AVGCOST*PRD_FRAC))/(PRD_HRGJUAL/1.11)*100)
          ELSE (((PRD_HRGJUAL-(ST_AVGCOST*PRD_FRAC))/PRD_HRGJUAL)*100)
        END AS MARGIN_A,
  
        CASE
          WHEN PRD_UNIT='KG'
          THEN (((PRD_HRGJUAL-(ST_LASTCOST*PRD_FRAC/1000))/PRD_HRGJUAL)*100)
          WHEN COALESCE(prd_flagbkp1,'T') ='Y' and COALESCE(prd_flagbkp2,'T') ='Y'
          THEN (((PRD_HRGJUAL/1.11)-(ST_LASTCOST*PRD_FRAC))/(PRD_HRGJUAL/1.11)*100)
          ELSE (((PRD_HRGJUAL-(ST_LASTCOST*PRD_FRAC))/PRD_HRGJUAL)*100)
        END AS MARGIN_L
  
FROM
(SELECT SUBSTR(PRD_PRDCD,1,6)
  ||0 PLU,
  PRD_PRDCD,
  PRD_KODEDIVISI,
  PRD_KODEDEPARTEMENT,
  PRD_KODEKATEGORIBARANG,
  PRD_KODETAG,
  PRD_DESKRIPSIPANJANG,
  PRD_UNIT,
  PRD_FRAC,
  PRD_HRGJUAL,
  prd_flagbkp1,
  prd_flagbkp2
FROM tbmaster_prodmast
)prd LEFT JOIN
(SELECT ST_PRDCD,
  ST_SALDOAKHIR,
  ST_LASTCOST,
  ST_AVGCOST
FROM tbmaster_Stock
WHERE st_lokasi='01'
)stk ON prd.PLU=stk.st_prdcd 
  WHERE COALESCE (PRD_KODETAG,'0') NOT IN ('N','X','Z') ORDER BY PRD_PRDCD ASC)HRG_N LEFT JOIN 
 (SELECT PRMD_PRDCD AS PLUMD,
  PRMD_HRGJUAL, SETT_PROMOMD
FROM TBTR_PROMOMD
LEFT JOIN (SELECT ALK_PRDCD, COUNT(ALK_MEMBER) SETT_PROMOMD FROM TBTR_PROMOMD_ALOKASI GROUP BY ALK_PRDCD) ALK ON ALK_PRDCD = PRMD_PRDCD
WHERE CURRENT_DATE BETWEEN DATE(PRMD_TGLAWAL) AND DATE(PRMD_TGLAKHIR)
)PRMD ON HRG_N.PRD_PRDCD=PRMD.PLUMD)MARGINM WHERE (MARGIN_A<=0 OR MARGIN_A_MDS<=0) AND PRD_PRDCD LIKE '%0'
`;

/**
 * SQL Query untuk Mengambil PLU yang Dimatikan oleh Master MD (Tag Z Hari Ini)
 */
const DEFAULT_PLU_MD_QUERY = `
SELECT * FROM tbtr_update_plu_md
WHERE upd_prdcd LIKE '%0'
  AND upd_atribute1 IS NULL
  AND upd_atribute2 = 'Z'
  AND CAST(upd_create_dt AS DATE) = CURRENT_DATE
ORDER BY upd_create_dt DESC
LIMIT 100;
`;

module.exports = {
  DEFAULT_MARGIN_QUERY,
  DEFAULT_PLU_MD_QUERY
};

